const translations = {
    en: {
        title: "Glossary",
        subtitle: "Key concepts related to Color Theory, Sustainability and Circular Economy.",

        headers: ["English", "Spanish", "Definition"],

        rows: [
            ["Color Theory","Teoría del color","Study of how colors interact and create visual effects."],
            ["Color Palette","Paleta de colores","A selected group of colors used in a design."],
            ["Hue","Matiz","The basic characteristic that identifies a color."],
            ["Saturation","Saturación","The intensity or purity of a color."],
            ["Contrast","Contraste","The visual difference between colors or elements."],
            ["Sustainability","Sostenibilidad","Meeting present needs without harming future generations."],
            ["Sustainable Development","Desarrollo sostenible","Development that balances economic, social and environmental goals."],
            ["Circular Economy","Economía circular","An economic model focused on reusing and recycling resources."],
            ["Recycling","Reciclaje","The process of converting waste into reusable materials."],
            ["Upcycling","Suprareciclaje","Creating higher-value products from discarded materials."],
            ["Renewable Energy","Energía renovable","Energy obtained from naturally replenished resources."],
            ["Carbon Footprint","Huella de carbono","The amount of greenhouse gases generated by an activity."],
            ["Waste Management","Gestión de residuos","The collection, treatment and disposal of waste materials."],
            ["Eco-design","Ecodiseño","Designing products with environmental impact in mind."],
            ["Green Economy","Economía verde","An economy that promotes sustainability and environmental protection."]
        ]
    },

    es: {
        title: "Glosario",
        subtitle: "Conceptos clave sobre teoría del color, sostenibilidad y economía circular.",

        headers: ["Inglés", "Español", "Definición"],

        rows: [
            ["Color Theory","Teoría del color","Estudio de cómo los colores interactúan y generan efectos visuales."],
            ["Color Palette","Paleta de colores","Conjunto de colores usados en un diseño."],
            ["Hue","Matiz","Característica básica que identifica un color."],
            ["Saturation","Saturación","Intensidad o pureza de un color."],
            ["Contrast","Contraste","Diferencia visual entre colores o elementos."],
            ["Sustainability","Sostenibilidad","Satisfacer necesidades actuales sin afectar el futuro."],
            ["Sustainable Development","Desarrollo sostenible","Desarrollo que equilibra lo económico, social y ambiental."],
            ["Circular Economy","Economía circular","Modelo basado en reutilizar y reciclar recursos."],
            ["Recycling","Reciclaje","Transformación de residuos en nuevos materiales."],
            ["Upcycling","Suprareciclaje","Crear productos de mayor valor a partir de residuos."],
            ["Renewable Energy","Energía renovable","Energía de fuentes naturales renovables."],
            ["Carbon Footprint","Huella de carbono","Emisiones de gases de efecto invernadero."],
            ["Waste Management","Gestión de residuos","Proceso de manejo de residuos."],
            ["Eco-design","Ecodiseño","Diseño con enfoque ambiental."],
            ["Green Economy","Economía verde","Economía orientada a la sostenibilidad."]
        ]
    }
};

let currentLang = "en";

const btn = document.getElementById("langBtn");

function updateTable(lang){
    const data = translations[lang];

    document.querySelector(".glossary-title").textContent = data.title;
    document.querySelector(".glossary-subtitle").textContent = data.subtitle;

    const ths = document.querySelectorAll("thead th");
    ths.forEach((th, i) => {
        th.textContent = data.headers[i];
    });

    const rows = document.querySelectorAll("tbody tr");

    rows.forEach((row, i) => {
        const cols = row.querySelectorAll("td");
        cols[0].textContent = data.rows[i][0];
        cols[1].textContent = data.rows[i][1];
        cols[2].textContent = data.rows[i][2];
    });

    btn.textContent = lang === "en" ? "ES" : "EN";
}

btn.addEventListener("click", () => {
    currentLang = currentLang === "en" ? "es" : "en";
    updateTable(currentLang);
});

updateTable("en");